### ISSUE TITLE
In sync with upstream version 1.6.20

### ISSUE THREAD

**Issue by joerg-krause** [medoc92/pupnp16#1]
Gladly, upstream has released version 1.6.20 some time ago which includes all patches you keep in the pupnp16-fixes branch. Maybe you can update the README about this?

**Comment by medoc92** [comment]
J�rg Krause writes:
 > Gladly, upstream has released version 1.6.20 some time ago which includes all
 > patches you keep in the pupnp16-fixes branch. Maybe you can update the README
 > about this?

Unfortunately, it seems that they did not include the main change, the one
preventing a non-responding subscribed control point to freeze the device,
(patches 57/58/59 in there: https://sourceforge.net/p/pupnp/patches/)

So I need to keep my version up. Believe me, I'd really be glad to get rid
of it !

jf

**Comment by joerg-krause** [comment]
Damn, you're right! I missed this one. Don't understand why this is not already applied!
